export type AirportCity = {
  city: string;
  country: string;
  code: string;
  airports?: string;
};

export const airportCities: AirportCity[] = [
  { city: "Montpellier", country: "France", code: "MPL", airports: "Montpellier-Méditerranée" },
  { city: "Paris", country: "France", code: "PAR", airports: "Charles-de-Gaulle, Orly, Beauvais" },
  { city: "Lyon", country: "France", code: "LYS", airports: "Saint-Exupéry" },
  { city: "Marseille", country: "France", code: "MRS", airports: "Marseille-Provence" },
  { city: "Nice", country: "France", code: "NCE", airports: "Nice-Côte d’Azur" },
  { city: "Toulouse", country: "France", code: "TLS", airports: "Toulouse-Blagnac" },
  { city: "Bordeaux", country: "France", code: "BOD", airports: "Bordeaux-Mérignac" },
  { city: "Nantes", country: "France", code: "NTE", airports: "Nantes-Atlantique" },
  { city: "Lille", country: "France", code: "LIL", airports: "Lille-Lesquin" },
  { city: "Strasbourg", country: "France", code: "SXB", airports: "Strasbourg-Entzheim" },
  { city: "Barcelone", country: "Espagne", code: "BCN", airports: "El Prat" },
  { city: "Madrid", country: "Espagne", code: "MAD", airports: "Adolfo-Suárez" },
  { city: "Séville", country: "Espagne", code: "SVQ" },
  { city: "Malaga", country: "Espagne", code: "AGP" },
  { city: "Lisbonne", country: "Portugal", code: "LIS", airports: "Humberto-Delgado" },
  { city: "Porto", country: "Portugal", code: "OPO" },
  { city: "Londres", country: "Royaume-Uni", code: "LON", airports: "Heathrow, Gatwick, Stansted, Luton" },
  { city: "Manchester", country: "Royaume-Uni", code: "MAN" },
  { city: "Rome", country: "Italie", code: "ROM", airports: "Fiumicino, Ciampino" },
  { city: "Milan", country: "Italie", code: "MIL", airports: "Malpensa, Linate, Bergame" },
  { city: "Venise", country: "Italie", code: "VCE", airports: "Marco-Polo" },
  { city: "Naples", country: "Italie", code: "NAP" },
  { city: "Amsterdam", country: "Pays-Bas", code: "AMS", airports: "Schiphol" },
  { city: "Bruxelles", country: "Belgique", code: "BRU", airports: "Brussels Airport" },
  { city: "Berlin", country: "Allemagne", code: "BER" },
  { city: "Francfort", country: "Allemagne", code: "FRA" },
  { city: "Munich", country: "Allemagne", code: "MUC" },
  { city: "Vienne", country: "Autriche", code: "VIE" },
  { city: "Prague", country: "Tchéquie", code: "PRG" },
  { city: "Budapest", country: "Hongrie", code: "BUD" },
  { city: "Athènes", country: "Grèce", code: "ATH" },
  { city: "Santorin", country: "Grèce", code: "JTR" },
  { city: "Istanbul", country: "Turquie", code: "IST" },
  { city: "Copenhague", country: "Danemark", code: "CPH" },
  { city: "Stockholm", country: "Suède", code: "STO" },
  { city: "Oslo", country: "Norvège", code: "OSL" },
  { city: "Reykjavik", country: "Islande", code: "REK" },
  { city: "Alger", country: "Algérie", code: "ALG", airports: "Houari-Boumédiène" },
  { city: "Oran", country: "Algérie", code: "ORN" },
  { city: "Constantine", country: "Algérie", code: "CZL" },
  { city: "Marrakech", country: "Maroc", code: "RAK" },
  { city: "Casablanca", country: "Maroc", code: "CMN", airports: "Mohammed-V" },
  { city: "Tanger", country: "Maroc", code: "TNG" },
  { city: "Tunis", country: "Tunisie", code: "TUN", airports: "Tunis-Carthage" },
  { city: "Djerba", country: "Tunisie", code: "DJE" },
  { city: "Le Caire", country: "Égypte", code: "CAI" },
  { city: "Dubaï", country: "Émirats arabes unis", code: "DXB" },
  { city: "Abou Dabi", country: "Émirats arabes unis", code: "AUH" },
  { city: "Doha", country: "Qatar", code: "DOH" },
  { city: "Djeddah", country: "Arabie saoudite", code: "JED" },
  { city: "Riyad", country: "Arabie saoudite", code: "RUH" },
  { city: "New York", country: "États-Unis", code: "NYC", airports: "JFK, Newark, LaGuardia" },
  { city: "Miami", country: "États-Unis", code: "MIA" },
  { city: "Los Angeles", country: "États-Unis", code: "LAX" },
  { city: "Montréal", country: "Canada", code: "YMQ", airports: "Trudeau, Saint-Hubert" },
  { city: "Toronto", country: "Canada", code: "YTO", airports: "Pearson, Billy-Bishop" },
  { city: "Mexico", country: "Mexique", code: "MEX" },
  { city: "Pointe-à-Pitre", country: "Guadeloupe", code: "PTP" },
  { city: "Fort-de-France", country: "Martinique", code: "FDF" },
  { city: "Bangkok", country: "Thaïlande", code: "BKK" },
  { city: "Bali", country: "Indonésie", code: "DPS", airports: "Denpasar-Ngurah Rai" },
  { city: "Jakarta", country: "Indonésie", code: "JKT" },
  { city: "Tokyo", country: "Japon", code: "TYO", airports: "Haneda, Narita" },
  { city: "Séoul", country: "Corée du Sud", code: "SEL", airports: "Incheon, Gimpo" },
  { city: "Singapour", country: "Singapour", code: "SIN", airports: "Changi" },
  { city: "Hô Chi Minh-Ville", country: "Vietnam", code: "SGN" },
  { city: "Hanoï", country: "Vietnam", code: "HAN" },
  { city: "Phuket", country: "Thaïlande", code: "HKT" },
  { city: "Sydney", country: "Australie", code: "SYD" },
];

export function findAirportCity(value: string) {
  const normalized = value.trim().toLocaleLowerCase("fr-FR");
  return airportCities.find(
    (item) => item.code.toLocaleLowerCase("fr-FR") === normalized || item.city.toLocaleLowerCase("fr-FR") === normalized || `${item.city} (${item.code})`.toLocaleLowerCase("fr-FR") === normalized,
  );
}
